apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-volume-config
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_management_agent,rabbitmq_shovel].
  rabbitmq.conf: | 
    management.load_definitions = /etc/rabbitmq/definitions.json
  definitions.json: |
    {
      "rabbit_version": "3.9.20",
      "rabbitmq_version": "3.9.20",
      "product_name": "RabbitMQ",
      "product_version": "3.9.20",
      "users": [
        {
          "name": "guest",
          "password_hash": "7Y8ROSwDnwRe46hyXRGDvnW00oygqL3Ub7NR6jP1BTEjS/GJ",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": [
            "administrator"
          ],
          "limits": {}
        },
        {
          "name": "holy",
          "password_hash": "54mkjJ4JwLCmqKaZ5CFGETpqLIE7zEZSQCeE70xJXSs7MhD0",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": [
            "administrator"
          ],
          "limits": {}
        },
        {
          "name": "user",
          "password_hash": "aNNOQeyQy7ADE0WcHwGJHgM/HdntDZHuk2psjgf6F5oHyoSr",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": [
            "administrator"
          ],
          "limits": {}
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "holy",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        },
        {
          "user": "user",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        },
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "topic_permissions": [],
      "parameters": [],
      "global_parameters": [
        {
          "name": "internal_cluster_id",
          "value": "rabbitmq-cluster-id-f9YQ1DLRgsy7Edo4Q5aeEw"
        }
      ],
      "policies": [],
      "queues": [],
      "exchanges": [],
      "bindings": []
    }