spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/notifications
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

