spring:
  config:
    activate:
      on-profile: dev


rabbitmq:
  host: localhost
  username: user
  password: password

  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    notification: internal.notification.routing-key