spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/notifications
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

rabbitmq:

  host: ${RABBIT_HOST}
  username: ${RABBIT_USERNAME}
  password: ${RABBIT_PASSWORD}

  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    notification: internal.notification.routing-key