spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/notifications
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: notifiedservice@gmail.com
    password: tkgqamfzeltfabdp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
