apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RABBITMQ_DEFAULT_USER: user
  RABBITMQ_DEFAULT_PASS: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.20-management-alpine
          ports:
            - containerPort: 15672
            - containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq/
            - name: rabbitmq-config-volume
              mountPath: /etc/rabbitmq/
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-claim
        - name: rabbitmq-config-volume
          configMap:
            name: rabbitmq-volume-config
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: internal
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672
    - name: external
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30672