apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-sender-service-config
data:
  MAIL_USERNAME: fixme
  MAIL_PASSWORD: fixme
  RABBIT_HOST: rabbitmq
  RABBIT_USERNAME: holy
  RABBIT_PASSWORD: holy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-sender-service
spec:
  selector:
    matchLabels:
      app: notification-sender-service
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-sender-service
    spec:
      containers:
        - name: notification-sender-service
          image: holydrug/notification-sender-service:1.2
          envFrom:
            - configMapRef:
                name: notification-sender-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: notification-sender-service
  labels:
    app: notification-sender-service
spec:
  type: NodePort
  selector:
    app: notification-sender-service
  ports:
    - name: internal
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30880
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-sender-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-sender-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
