spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: notifiedservice@gmail.com
    password: tkgqamfzeltfabdp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
server:
  port: 8081

rabbitmq:
  host: localhost
  username: guest
  password: guest

  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    notification: internal.notification.routing-key