spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true

rabbitmq:
  port: ${RABBIT_PORT}
  host: ${RABBIT_HOST}
  username: ${RABBIT_USERNAME}
  password: ${RABBIT_PASSWORD}

  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    notification: internal.notification.routing-key