spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: notifiedservice@gmail.com
    password: tkgqamfzeltfabdp
    properties:
      mail:
        smtp:
          starttls:
            enable: true

rabbitmq:
  host: localhost
  username: user
  password: password

  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    notification: internal.notification.routing-key